---
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("C:\\Users\\ningt\\Anaconda3\\envs\\myEnvironment\\python.exe",required = T)
use_condaenv("myEnvironment", required = T)
```

```{python data1}
import requests
response=requests.get("https://www.dropbox.com/s/58e3g2dq8urecw0/hw1-ans.Rmd?dl=1")
filelines=response.text.split("\n")
```


```{python ans12}
index_3ticks = []

for i in enumerate(filelines):
    x = filelines.index("```")
    index_3ticks.append(x)

index_3ticks
```

```{python}
ind = [i for i, x in enumerate(filelines) if "```" in x]
ind
```

```{python}
testlist = [1,2,3,5,3,1,2,1,6]    
position=0
for i in testlist:
   if i == 1:
      print(position)
   position=position+1
```

```{python ans14}
python_code_list = []

true_end = [i for i, x in enumerate(filelines) if x == "```"]
range(start[0],true_end[0])
[i for i in range(start[0],true_end[0])] 
[[i for i in range(start[i],true_end[i])] for i in range(len(start))]


code_number = [range(start[i]:end[i]) for i in range(len(start))]
[filelines[start[i]:end[i]] for i in range(len(start))]
python_code_list.append(filelines[])
# python_code_list
```


```{python data2}
import requests
response=requests.get("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3")
danceInfo=response.json()
```

```{python ans21}
allUIDs=[]
for i in range(len(danceInfo)):    
    allUIDs.append(danceInfo[i]["UID"])

allUIDs
```

```{python ans22}
def search_by_uid(uid):
    if uid in allUIDs:
        return uid
    
search_by_uid('5c76c26ed083a35404c3dce7')
# search_by_uid
```

```{python ans23}
updated_result = search_by_uid("5d35ec95d083a398fcdc5e14")
updated_result = updated_result.update({'time': '2019/10/30 15:00:00', 'location': '新北市三峽區大學路151號', 'locationName': '國立臺北大學'})
updated_result = search_by_uid("5d35ec95d083a398fcdc5e14")

updated_result
```

```{python data3}
M=[[7, -9, -5, 10, -13], 
    [12, -6, -3, -6, -14], 
    [7, -5, -4, 1, 5]]
```

```{python ans32}
M_partial=[]
x=[]
y=[]

for i in range(1,2):    
    for j in range(2,5):
        x.append(M[i][j])
for i in range(2,3):    
    for j in range(2,5):
        y.append(M[i][j])
        
M_partial.append(x)        
M_partial.append(y) 

M_partial
```

```{python ans33}
def matrix_get(matrix, rangeR, rangeC):
    M_partial=[]
    x=[]
    y=[]
    
    rangeR = "range(1,3)"
    word = rangeR.split()
    x0 = word[6]
    x1 = word[8]
    x0
    x1
     
    for i in range(1,2):    
        for j in range(2,5):
            x.append(M[i][j])
            
    M_partial.append(x)        
    M_partial.append(y) 
    return M_partial
    
# matrix_get
```

```{python ans33}
def matrix_get(matrix,rangeR,rangeC):

    M_partial=[]
    x=[]
    
    #rangeR = "range(1,3)" # delete
    #rangeC = "range(2,5)" # delete
    word1 = rangeR
    word2 = rangeC
    x0 = int(word1[6])
    x1 = int(word1[8])
    x2 = int(word2[6])
    x3 = int(word2[8])
    
    for z in range(x0,x1):
        for i in range(z,z+1):    
            for j in range(x2,x3):
                x.append(M[i][j])
            M_partial.append(x)
            x=[]
    
    return M_partial
    
matrix_get
```