---
title: "課堂練習"
date: "9/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(reticulate)
use_python("C:\\Users\\ningt\\Anaconda3\\envs\\myEnvironment\\python.exe",
           required = T)
use_condaenv("myEnvironment", required = T)
```

## 2.3 dictionary
### 2.3.1 增加元素
```{python}
dictionaryA={
  "date": [2001,2002,2003],
  "cost": [21000,33000,45880]}
dictionaryA

dictionaryA["number"]=[100,200,300] # 增加新的key-value pair
dictionaryA
```

```{python}
dictionaryA["date"] # 查詢
```


```{python data3}
import requests
response=requests.get("https://cloud.culture.tw/frontsite/trans/SearchShowAction.do?method=doFindTypeJ&category=3")
danceInfo=response.json()
```

```{python}
type(danceInfo)
```

### 2.3.2 檢視keys
```{python}
danceInfo[1].keys()
```

### 2.3.3 檢視values: values
```{python}
danceInfo[1].values()
```

### 2.3.6 取出key下的value: get
```{python}
danceInfo[1].get("showInfo")

danceInfo[1].get("showInfow","something wrong") # 若資料有錯會顯示something wrong
```

### 2.3.4 檢視成對(key, value): items
```{python}
dictionaryA.keys()
dictionaryA.values()
dictionaryA.items()
```

```{python}
dictionaryA.keys()
list(dictionaryA.keys())
list(dictionaryA.keys())[0]
```

### 2.3.5 檢查某key值存不存在: in (operation)
```{python}
"date" in dictionaryA
```

練習
```{python}
import pandas as pd

finStatement=pd.read_csv("http://mopsfin.twse.com.tw/opendata/t187ap06_O_ci.csv")
dict_finStatement=finStatement.to_dict()
```

```{r}
library(dplyr)
py$dict_finStatement %>% View
```

找出dict_finStatement中’營業利益（損失）‘為負的’公司名稱’

```{python}
dict_finStatement.get("營業利益（損失）")
dict_finStatement.get("公司名稱")
```

```{python}
listA=[10,2,7,3,8]

[listA[index] for index in range(len(listA)) if listA[index]>5] # 取數字
[index for index in range(len(listA)) if listA[index]>5] # 取位置
```

1. 找出損失的index
```{python}
profit=list(dict_finStatement.get("營業利益（損失）").values())

lossFirmKeys=[index for index in range(len(profit)) if profit[index]<0]
```

2. 由index進去公司找出名稱
```{python}
lossFirmKeys[100]
dict_finStatement.get("公司名稱")[index]
dict_finStatement.get("公司名稱").get(index)

[dict_finStatement.get("公司名稱").get(index) for index in lossFirmKeys]
```

```{python}
{dict_finStatement.get("公司名稱").get(index): list(dict_finStatement.get("營業利益（損失）").values())[index] for index in lossFirmKeys}
```

另解
```{python}
[dict_finStatement["公司名稱"][i] 
  for i in range(len(dict_finStatement["營業利益（損失）"])) 
  if dict_finStatement["營業利益（損失）"][i] < 0]
```

# Chapter 3
## 3.1 Function
```{python}
def myFun(x,y):
  z=x+y
  return z
  
myFun(5,6)
myFun(0,1)

def myFun2(x,y):
  return x+y
  
myFun2(5,6)
myFun2(0,1)
```

### 3.1.1 預設值
```{python}
def myFun3(x,y=6):
  return x+y
  
myFun3(y=5,x=6)
myFun3(5)
```

#### packing/unpacking
```{python}
listA=[0,1,3]

a,b,c=listA
a
b
c

a,*b=listA
a
b
```

```{python}
# (0,alpha=1,beta=3)

# def ...(a,**b)

# b={"alpha":1,"beta":3}
```

### 3.1.2 pack to tuple
```{python}
def test2(input1,*input3):
  print('input1 is ', input1)
  print('input3 is ', input3)
  return None
 
test2(1,1.2,4,5)
test2(1,[1.2,4],5)
test2(["1","b"],{2,5,7},10)
```

```{python}
def f(x, *seq, y):
    print("x is: ", x)
    print("seq is: ", seq)
    print("y is: ", y)
    return None

f(1, 2, 3, 4, 5)
f(1, 2, 3, 4, y=5)
```

### 3.1.3 unpacking usage
```{python}
a,b,c=(1,3,4)
a,b,c=(*[1,3],4)
a,b,c=(1,*[3,4])
a,b,c=(*[1,3,4])
```

練習
```{python}
def utility_cobb_douglass(x,y,alpha=1,beta=3):
  
  utilValue = x**alpha*y**beta
  
  return utilValue

utility_cobb_douglass(1,1,0.5,0.5)
utility_cobb_douglass(1,1)
```

```{python}
x,y,**parameters=(1,1,alpha=0.5,beta=0.5)
```

parameters={
"alpha":0.5
"beta":0.5
}

```{python}
def utility_cobb_douglass(x,y,**parameters):
  alpha=parameters["alpha"]
  beta=parameters["beta"]
  utilValue = x**alpha*y**beta
  return utilValue
```

## 3.3
```{python}
global1=[1,3,[4,5]]
def funtest(x):
  x[0]="a" # 深複製
  y=x[:] # 淺複製
  y[1]="b"
  y[2][1]="c" # 改到了原先記憶體位置的東西
  return None

global1
funtest(global1)
global1
```

```{python}
global1=[1,3,[4,5]]
funtest(global1.copy())
global1

import copy 
global1=[1,3,[4,5]]
funtest(copy.deepcopy(global1))
global1 # 深複製後絕對不會改到原先記憶體位置
```

